# Generated by Django 3.1 on 2022-10-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
